sonar.projectKey=lalaro_Backend_LifePill
sonar.organization=lalaro

# Carpeta principal del código fuente
sonar.sources=src

# Carpeta donde están los tests
sonar.tests=tests

# Ignorar node_modules y carpetas internas del sistema
sonar.exclusions=node_modules/**,.github/**

# Informe de cobertura (se generará con Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8
